# This is for replicating https://distill.pub/2020/growing-ca/

#weights_dir: '33'
weights_dir: '/root/NCA/ckpts/damage_ckpt/'
checkpoint_dir: '/root/NCA/ckpts/damage_ckpt'
pool_size: 1024 
target_filename: "emoji_imgs/smile.png"
n_damage: 1
learning_rate: 0.0001
total_training_steps: 100000
batch_size: 8 
num_nca_steps: 120
log_every: 200


