# This is for replicating https://distill.pub/2020/growing-ca/
# With damage to NCA

weights_dir: 'smile_works/nca_exp1/'
checkpoint_dir: 'ckpts/damage_ckpt'
pool_size: 1000
target_filename: "emoji_imgs/smile.png"
damage: True 
learning_rate: 0.0006
batch_size: 16


